import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import Button from "@material-tailwind/react/Button";
import Icon from "@material-tailwind/react/Icon";
import Doc from "../components/Doc";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Docs Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Doc />
      
    </div>
  );
}
