import Head from "next/head";
import Header from "../components/Header";
import Doc from "../components/Doc";
import RecentDocs from "../components/RecentDocs";
import { getSession, useSession } from 'next-auth/client';
import Login from "../components/Login";

export default function Home() {

  const {session} = useSession();

  if(!session) return (<Login/>)
  return (
    <div>
      <Head>
        <title>Google Docs Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
      <Header />
      <Doc />
      <RecentDocs />

    </div>
  );
}
